### ISSUE TITLE
question on gossip.

### ISSUE THREAD

**Issue by mmmeee1111** [Funatiq/gossip#6]
Hi gossip experts. Thanks for the open-source contribution.

I am faced with invalid resource handle error when running the gather&scatter benchmark.

Thanks

**Comment by mmmeee1111** [comment]
The all2all execution was fine. There were issues when I was running gather and scatter.

Afther I generated the plan for main_gpu, here, which is 0.

When I use the python scripts:
```
benchmark # python3 benchmark_plan.py scatter_gather scatter_plan.json gather_plan.json 
                                PROGRESS: size 1/16
                PROGRESS: repeat 1/3
Traceback (most recent call last):
  File "benchmark_plan.py", line 56, in <module>
    out = subprocess.check_output([exe, args.type, plans[0], plans[1], "--size", str(s)])
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/gossip/benchmark/execute', 'scatter_gather', '/gossip/benchmark/scatter_plan.json', '/gossip/benchmark/gather_plan.json', '--size', '12']' returned non-zero exit status 1
```

But when I switch to use the binary execute to run the gather and scatter:

```
./execute scatter_gather scripts/scatter_plan.json scripts/gather_plan.json --size 12
RUN: scatter_gather
INFO: 32768 bytes (scatter_gather)
TIMING: 0.467968 ms (malloc_devices)
TIMING: 1.59744 ms (zero_gpu_buffers)
TIMING: 0.475136 ms (init_data)
TIMING: 3.64442 ms (multisplit)

Partition Table:
470 489 534 553 514 515 538 483 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 

Required buffer sizes:
0 538 717 604 0 344 0 687 

TIMING: 3.94455e-31 ms (malloc_buffers)
CUDA error: invalid resource handle : executor.cuh, line 405
```

do you have any idea?

**Comment by mmmeee1111** [comment]
Hi, I can run scatter_gather using the simple plan /plans/dgx1_direct/gather.json. But when I tried /plans/dgx1_opt/gather.json. `./execute scatter_gather plans/dgx1_opt/scatter_plan.json plans/dgx1_opt/gather_plan.json` This error occurs:

```
RUN: scatter_gather
TIMING: 108.35 ms (malloc_devices)
TIMING: 9.8304 ms (zero_gpu_buffers)
INFO: 2147483648 bytes (scatter_gather)
TIMING: 3.74784 ms (init_data)
TIMING: 56.2104 ms (multisplit)

Partition Table:
33553989 33562958 33552866 33555233 33552206 33551309 33550824 33556071
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0

Required buffer sizes:
0 22367539 27963066 44740099 44737216 0 0 5591804

TIMING: 5.25803e-09 ms (malloc_buffers)
CUDA error: invalid resource handle : include/gossip/context.cuh, line 180
```

So i generated my own plan using the `plan_from_topology_asynch.py`, and I attached the gather_plan.json:
```
{"num_chunks": 6, "num_gpus": 8, "main_gpu": 0, "chunks": [6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], "num_steps": 14, "type": "gather", "plan": 
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], 
[1, 1, 1, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[1, 1, 1, 3, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0], 
[3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[3, 3, 3, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0], 
[3, 3, 3, 3, 3, 3, 2, 2, 2, 0, 0, 0, 0, 0, 0], 
[3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0], 
[3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 0, 0, 0, 0, 0], 
[4, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0],
 [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 0, 0], 
[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 2, 2, 0], 
[4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 7, 0], 
[4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 0, 0], 
[4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 0, 0, 0], 
[5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0], 
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 0, 0, 0, 0], 
[5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 0, 0, 0, 0, 0], 
[5, 5, 5, 5, 5, 5, 5, 7, 0, 0, 0, 0, 0, 0, 0], 
[5, 5, 5, 5, 5, 5, 7, 0, 0, 0, 0, 0, 0, 0, 0], 
[5, 5, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[6, 6, 6, 6, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0], 
[6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 3, 0, 0, 0, 0], 
[6, 6, 6, 6, 6, 6, 1, 1, 1, 3, 3, 2, 0, 0, 0], 
[6, 6, 6, 6, 6, 6, 6, 1, 3, 2, 2, 2, 2, 0, 0], 
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 0, 0, 0, 0], 
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 0, 0], 
[7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
[7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0]]}
```
The same error occurs:

```
RUN: scatter_gather
TIMING: 0.508928 ms (malloc_devices)
TIMING: 0.206848 ms (zero_gpu_buffers)
INFO: 32768 bytes (scatter_gather)
TIMING: 0.095232 ms (init_data)
TIMING: 0.620544 ms (multisplit)

Partition Table:
470 489 534 553 514 515 538 483
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0

Required buffer sizes:
0 538 717 604 0 344 0 687

TIMING: 1.78114e+12 ms (malloc_buffers)
CUDA error: invalid resource handle : include/gossip/context.cuh, line 180
```

Anyone can help me figure out whats happening for gather and scatter?

**Comment by Funatiq** [comment]
Hi! Thank you for the error investigation. I guess you also used the plan /plans/dgx1_direct/scatter.json in the working example?
It seems like there is an error in the buffer allocation. The direct transfer plans do not use any buffers. Unfortunately, I am not able to reproduce the error. You could try to use `mems_lens` instead of `bufs_lens` for buffer allocation in [line 396](https://github.com/Funatiq/gossip/blob/4b7f6428ce59660751b04679a6be58a2a43a05cf/executor.cuh#L396) and [line 443](https://github.com/Funatiq/gossip/blob/4b7f6428ce59660751b04679a6be58a2a43a05cf/executor.cuh#L443) of `executor.cuh`.

**Comment by mmmeee1111** [comment]
Hi I followed your instruction to update the buffer allocation. But there are same errors:

```
RUN: scatter_gather
INFO: 32768 bytes (scatter_gather)
TIMING: 0.463872 ms (malloc_devices)
TIMING: 0.232448 ms (zero_gpu_buffers)
TIMING: 0.082944 ms (init_data)
TIMING: 0.637952 ms (multisplit)

Partition Table:
470 489 534 553 514 515 538 483
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0

Required buffer sizes:
0 538 717 604 0 344 0 687

TIMING: 3.94455e-31 ms (malloc_buffers)
CUDA error: invalid resource handle : executor.cuh, line 405
```

I found there was similar #4  before.

**Comment by mmmeee1111** [comment]
I am so curious that all2all benchmark can be executed successfully. But for gather&scatter, the invalid resource handle errors always occur. Do you have any idea?

**Comment by Funatiq** [comment]
There was a problem in the timers, which did not use the correct device in some cases. I replaced the whole cudahelpers submodule with a new version from our group (https://github.com/Funatiq/gossip/commit/120661a15cd7b1de7ff69a893a53059f1c20aab2). This should resolve this issue and https://github.com/Funatiq/gossip/issues/4.
